services: 
  web:
    container_name: stonable_web
    build: docker
    restart: always
    volumes:
      - ./docker:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
  db:
    container_name: stonable_postgres
    image: postgres:16.3-alpine3.20
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
volumes:
  postgres-data:
