# Generated by Django 5.0.6 on 2024-06-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entite',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='entite',
            name='prenom',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
