# Generated by Django 5.0.6 on 2024-06-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonable', '0002_alter_entite_nom_alter_entite_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entite',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
    ]
