# Generated by Django 5.0.6 on 2024-06-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonable', '0003_alter_entite_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entite',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
