# Generated by Django 5.0.6 on 2024-06-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonable', '0004_alter_entite_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entite',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
